#!/bin/sh

# Only check when the container is started with the default CMD.
if [ "$*" = "/usr/local/bin/uwsgi --ini /usr/local/etc/uwsgi.ini" ]; then
  # For local development, avoid having to exec into the container for a test db.
  # For production, migrate the database using an AWS single task definition or Kubernetes initContainer.
  if [ "$DATABASE_URL" = "sqlite:////tmp/demo.db" ]; then
    echo '** No $DATABASE_URL is configured, generating example data for local development' >&2
    manage.py migrate
  fi

  manage.py check --deploy
fi


exec "$@"
